name = "portfolio-app"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

# pages_build_output_dir = ".vercel/output/static"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "8dbddc468fdb4660841b78a4acb8c6a6"
